# Generated by Django 4.0.4 on 2022-06-15 10:32

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('address_1', models.CharField(max_length=100, null=True, verbose_name='Address')),
                ('address_2', models.CharField(max_length=100, null=True, verbose_name='Address 1')),
                ('town', models.CharField(max_length=100, null=True, verbose_name='Town/City')),
                ('postcode', models.CharField(max_length=8, null=True, verbose_name='Post Code')),
                ('county', models.CharField(max_length=100, null=True, verbose_name='County')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.addressdetails'),
        ),
    ]
