# Generated by Django 3.2.14 on 2022-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_addressdetails_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdetails',
            name='address_1',
            field=models.CharField(default='', max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='address_2',
            field=models.CharField(default='', max_length=100, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='county',
            field=models.CharField(default='', max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='postcode',
            field=models.CharField(default='', max_length=8, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='addressdetails',
            name='town',
            field=models.CharField(default='', max_length=100, verbose_name='Town/City'),
        ),
    ]
