# Generated by Django 4.0.4 on 2022-07-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='description',
            field=models.TextField(blank=True, default='Great product!'),
        ),
    ]
