# Generated by Django 4.0.4 on 2022-07-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_productreview_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
