# Generated by Django 4.0.4 on 2022-06-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_bill_pence',
            new_name='bill_pence',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_address',
        ),
    ]
