# Generated by Django 4.0.4 on 2022-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderstatus_alter_order_status_delete_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
