# Generated by Django 4.0.4 on 2022-06-30 10:54

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status_delete_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
