# Generated by Django 4.0.4 on 2022-06-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_short_description'),
        ('basket', '0002_alter_basket_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BasketProducts',
            new_name='BasketProduct',
        ),
    ]
